spring:
  application:
    name: PRODUCT-MGMT-SYSTEM
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8001