spring:
  application:
    name: PRODUCT-MGMT-SYSTEM
  graphql:
    graphiql:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
server:
  port: 8002